import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { epicPro, inter } from "@/fonts/fonts";
import "./globals.css";
import { ThemeProviders } from "@/providers/themeProvider";
import { Navbar } from "@/components/layout/navbar/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${epicPro.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProviders>
          <Navbar trigger="onHover" />
          {children}
        </ThemeProviders>
      </body>
    </html>
  );
}
